vim.keymap.set("n","<C-p>", ":Telescope<CR>")
vim.keymap.set("n","<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
vim.keymap.set("n","<Leader>ff", function()
    require('telescope.builtin').find_files()
end)

vim.keymap.set("n","<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
vim.keymap.set("n","<leader>fg", function()
    require('telescope.builtin').live_grep()
end)
vim.keymap.set("n","<leader>fb", function()
    require('telescope.builtin').buffers()
end)
vim.keymap.set("n","<leader>fh", function()
    require('telescope.builtin').help_tags()
end)

vim.keymap.set("n","<leader>vrc", function()
    require('insayt.telescope').search_dotfiles({ hidden = true })
end)
vim.keymap.set("n","<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
vim.keymap.set("n","<leader>gm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
